/var/folders/sr/kzpyqt5d5xs0lx_nqllhbvcm0000gn/T/TestWalkThroughFiles1361806823/001/dir2795579013/dir24026705026/file3.txt: ../../../../../bookera-extensions-hub/packages/shared/module/module
/var/folders/sr/kzpyqt5d5xs0lx_nqllhbvcm0000gn/T/TestWalkThroughFiles1361806823/001/file1.txt: ../../../bookera-extensions-hub/packages/shared/module/module
